#!/bin/bash

export TEXTDOMAIN=rpi-pacstrap
export TEXTDOMAINDIR=/usr/local/share/locale

. gettext.sh

set -e

if [ `whoami` != 'root' ]; then
	PROGNAME=$0
	echo $(eval_gettext "Script must be run as root, try: \${PROGNAME}") ; echo
	exit 1
fi

[ -z ${PS_ROOTPWD} ] && PS_ROOTPWD=root
[ -z ${PS_HOSTNAME} ] && PS_HOSTNAME=alarmpi
[ -z ${PS_USERNAME} ] && PS_USERNAME=alarm
[ -z ${PS_USERPWD} ] && PS_USERPWD=alarm

if ! test -z ${1} ; then
	rootfs=${1}
fi

packagelist=$(mktemp)

cat /dev/stdin > "${packagelist}"

if mount | grep "${rootfs}" > /dev/null; then
	# it's a mount point (device mounted)
	echo $(eval_gettext "Pacstrapping arch root filesystem into \${rootfs}") ; echo
	echo $(eval_gettext "Target: \${rootfs} is a mounted partition") ; echo
	pacstrap "${rootfs}" $(cat ${packagelist}) 
else
	# no it's not a mounted mount point
	echo $(eval_gettext "Target \${rootfs} is a directory") ; echo
	pacstrap -d "${rootfs}" $(cat ${packagelist})
fi

sync

# Add a udev rule to make vichiq 0777
echo $(gettext "Adding udev rules to /etc/udev/rules.d/raspberrypi.rules") ; echo
rules=$(cat <<EOF
SUBSYSTEM==\"vchiq|input\", MODE=\"0777\"
KERNEL==\"mouse*|mice|event*\",  MODE=\"0777\"
EOF
)
input="echo -e \"${rules}\" > /etc/udev/rules.d/raspberrypi.rules"
arch-chroot "${rootfs}" /bin/bash -c "${input}"

# add a line to /etc/fstab to mount the boot partition
echo $(gettext "Adding lines to /etc/fstab") ; echo
input="echo -e \"\n\n/dev/mmcblk0p1  /boot   vfat    defaults        0       0\n\n\" >> /etc/fstab"
arch-chroot "${rootfs}" /bin/bash -c "${input}"

# set hostname
echo $(eval_gettext "Set hostname to \${PS_HOSTNAME}") ; echo
input="echo \"${PS_HOSTNAME}\" > /etc/hostname"
arch-chroot "${rootfs}" /bin/bash -c "${input}"

# set root password
echo $(eval_gettext "Set root password to \${PS_ROOTPWD}") ; echo
input="echo -e \"${PS_ROOTPWD}\n${PS_ROOTPWD}\n\" | passwd root"
arch-chroot "${rootfs}" /bin/bash -c "${input}"

# add new user
echo $(eval_gettext "Add user \${PS_USERNAME}") ; echo
input="useradd -m -g users -G wheel,storage,power -s /bin/bash ${PS_USERNAME}"
arch-chroot "${rootfs}" /bin/bash -c "${input}"

# set user password
echo $(eval_gettext "Set password for user \${PS_USERNAME} to ${PS_USERPWD}") ; echo
input="echo -e \"${PS_USERPWD}\n${PS_USERPWD}\n\" | passwd ${PS_USERNAME}"
arch-chroot "${rootfs}" /bin/bash -c "${input}"

#
# Two services are enabled if they are installed:
#  1. dhcpcd
#  2. openssh (sshd)
#

# Enable dhcpcd.service if installed
if arch-chroot "${rootfs}" /bin/bash -c "which dhcpcd &>/dev/null" ; then
	echo $(gettext "Enabling dhcpcd.service") ; echo
	arch-chroot "${rootfs}" /bin/bash -c "systemctl enable dhcpcd.service"
else
	echo ${gettext "dhcpcd is not installed") ; echo
fi

# Enable sshd.service if installed
if arch-chroot "${rootfs}" /bin/bash -c "which sshd &>/dev/null" ; then
	echo $(gettext "Enabling sshd.service") ; echo
	arch-chroot "${rootfs}" /bin/bash -c "systemctl enable sshd.service"
else
	echo $(gettext "openssh is not installed") ; echo
fi

echo $(gettext "All done") ; echo

exit 0

