#!/bin/bash

export TEXTDOMAIN=pacstrap-alarmpi
export TEXTDOMAINDIR=/usr/local/share/locale

. gettext.sh

set -e

if [ `whoami` != 'root' ]; then
	progname=$0
	echo $(eval_gettext "Must be run as root, try: sudo \${progname}") ; echo
	exit 1
fi

chrootdir=0

while getopts ":d" opt
do
	case $opt in
		d)
			chrootdir=1
		;;
		\?)
			echo "Usage: ./foo.sh [-d] <directory>"
			exit 1
		;;
	esac
done

shift $(($OPTIND -1 ))

chroot_="${1}"

[ -d "${chroot_}" ] || mkdir -p "${chroot_}"


if [ ${chrootdir} = '1' ]; then
	pacstrap -d "${chroot_}" base linux-raspberrypi linux-raspberrypi-headers raspberrypi-firmware openssh sudo
else
	pacstrap "${chroot_}" base linux-raspberrypi linux-raspberrypi-headers raspberrypi-firmware openssh sudo
fi

cp /boot/*.bin "${chroot_}"/boot
cp /boot/*.dat "${chroot_}"/boot
cp /boot/*.elf "${chroot_}"/boot

chroot "${chroot_}"/ mknod -m 600 /dev/console c 5 1
chroot "${chroot_}"/ mknod -m 666 /dev/null c 1 3
chroot "${chroot_}"/ mknod -m 666 /dev/zero c 1 5

chroot "${chroot_}" /bin/bash -c 'echo "alarmpi" > /etc/hostname'

chroot "${chroot_}" /bin/bash -c 'echo -e "\n\n/dev/mmcblk0p1  /boot   vfat    defaults        0       0\n\n" >> /etc/fstab'

chroot "${chroot_}" /bin/bash -c 'echo "SSHD: ALL" >> /etc/hosts.allow'


# set root password
echo -e "root\nroot\n" | chroot "${chroot_}" /usr/bin/passwd root


# add a user and set the password
chroot "${chroot_}" useradd -m -g users -G wheel,storage,power -s /bin/bash alarm
echo -e "alarm\nalarm\n" | chroot "${chroot_}" /usr/bin/passwd alarm


chroot "${chroot_}" systemctl enable dhcpcd.service
chroot "${chroot_}" systemctl enable sshd.service

echo $(gettext "All done") ; echo


