#!/bin/bash

if [ $(id -u) -ne 0 ]; then
    echo "Script must be run as root.  Try 'sudo knl_deploy'"
    exit 1
fi

if [ ! -f /mnt/rpi-boot/cmdline.txt ]; then
    echo "It looks like there is no valid Raspberry Pi boot partition mounted at /mnt/rpi-boot"
    echo "Can't deploy the new kernel"
    exit 1
fi

cp ${KERNEL_BUILD}/arch/arm/boot/Image /mnt/rpi-boot/kernel.img





