#!/bin/bash
# Builds the kernel modules saving the output messages in modules.script


if [ $# -ne 1 ]; then
	echo "Usage: $0 <kernel-root>"
	echo "Example: $0 ~/linux-rpi-3.6.y"
	echo
	exit 1
fi

if [ ! -d $1 ]; then
	echo "There is no path to $1"
	exit 1
fi

if [ ! -f "$1/linux/MAINTAINERS" ]; then
	echo "$1/linux does not look like a valid kernel source tree"
	exit 1
fi

# will faile if the path to the script contains an underscore:
BN=`$(basename $0)
SCRPT=${BN##*_}.script

export KERNEL_ROOT=$1

# this has to come after KERNEL_ROOT is set above:
[[ -f ~/.knl_exports ]] && . ~/.knl_exports


cd ${KERNEL_SRC}
date > ${SCRPT}
echo "KERNEL_ROOT: ${KERNEL_ROOT}"
echo "KERNEL_ROOT: ${KERNEL_ROOT}" >> ${SCRPT}

echo "KERNEL_SRC: ${KERNEL_SRC}"
echo "KERNEL_SRC: ${KERNEL_SRC}" >> ${SCRPT}

echo "CCPREFIX: ${CCPREFIX}"
echo "CCPREFIX: ${CCPREFIX}" >> ${SCRPT}

make O=${KERNEL_BUILD} ARCH=arm CROSS_COMPILE=${CCPREFIX} modules &>> ${SCRPT}
RES=$?
date >> ${SCRPT}
 exit ${RES}

