#!/bin/bash


export TEXTDOMAIN=rpi-pacstrap
export TEXTDOMAINDIR=/usr/local/share/locale

. gettext.sh

. rpi-pacstrap.lib

usage() {
	usage="this is the usage"
	echo $usage
}

set -e

check_root result_
if [ ${result_} != 1 ]; then
	PROGNAME=$0
	echo $(eval_gettext "Script must be run as root, try: sudo \$PROGNAME") ; echo
	exit 1
fi

# set up and test defaults
datapath=/usr/local/share/rpi-pacstrap/data

if test -z ${RPI_ROOTFS_PATH} ; then
	RPI_ROOTFS_PATH=/mnt/rootfs
fi

if test -z ${RPI_PACSTRAP_PACKAGE_LIST} ; then
	RPI_PACSTRAP_PACKAGE_LIST=${datapath}/rpi_pacstrap_package_list.txt
fi

if test -z ${RPI_HOSTNAME} ; then
	RPI_HOSTNAME=alarmpi
fi

if test -z ${RPI_ROOTPWD} ; then
	RPI_ROOTPWD=root
fi

if test -z ${RPI_USERNAME} ; then
	RPI_USERNAME=alarm
fi

if test -z ${RPI_USERPWD} ;then
	RPI_USERPWD=alarm
fi


while getopts ":l:n" opt
do
	case $opt in
		n)
			dryrun_=1
		;;
		l)
			RPI_PACSTRAP_PACKAGE_LIST="${OPTARG}"
		;;
		\?)
			usage
			exit 1
		;;
	esac
done

shift $(($OPTIND -1 ))

if ! test -z ${1} ; then
	RPI_ROOTFS_PATH=${1}
fi

if ! test -z ${dryrun_} ; then
	echo -e "\nDry run detected:\n\n"
	echo "Root file system path: ${RPI_ROOTFS_PATH}"
	echo "Package list: ${RPI_PACSTRAP_PACKAGE_LIST}"
	echo "Host name: ${RPI_HOSTNAME}"
	echo "Root password: ${RPI_ROOTPWD}"
	echo "User: ${RPI_USERNAME}"
	echo "User password: ${RPI_USERPWD}"
	echo
	exit 0
fi

if [ ! -r ${RPI_PACSTRAP_PACKAGE_LIST} ]; then
	echo $(eval_gettext "Package list: \${RPI_PACSTRAP_PACKAGE_LIST} does not exist or is not readable") 
	exit 1
fi


if mount | grep "${RPI_ROOTFS_PATH}" > /dev/null; then
	# it's a mount point (device mounted)
	echo $(eval_gettext "Pacstrapping arch root filesystem into \${RPI_ROOTFS_PATH}")
	echo $(eval_gettext "Target: \${RPI_ROOTFS_PATH} is a mounted partition")
pacstrap "${RPI_ROOTFS_PATH}" $(cat ${RPI_PACSTRAP_PACKAGE_LIST}) 
else
	# no it's not a mounted mount point
	echo $(eval_gettext "Target \${RPI_ROOTFS_PATH} is a directory")
	[ -d "${RPI_ROOTFS_PATH}" ] || mkdir "${RPI_ROOTFS_PATH}"
	pacstrap -d "${RPI_ROOTFS_PATH}" $(cat ${RPI_PACSTRAP_PACKAGE_LIST})
fi

sync

echo $(gettext "Completed pacstrap of base file system")

exit 0

