#!/bin/bash

echo "Adding the user: ${1}..."
useradd -m -g users -G audio,lp,storage,video,wheel,games,power,pulse,pulse-access -s /bin/bash "${1}" || exit 1
echo "Added new user ${1} successfully"

exit 0





