#!/bin/bash

BUILDS=~/.builds
ARCH="'armv6h'"

function do_pkgbuild_edit {
	( mv PKGBUILD PKGBUILD.old && cat PKGBUILD.old | perl -e "while(<>) {s/^arch=\('i686'\s+'x86_64'\)$/arch=\('i686' 'x86_64' ${ARCH}\)/;print;}" > PKGBUILD ) || return 1
	return 0
}

## main code

sudo true

if [ ! ${BUILDS} ]; then
	${BUILDS}=~/.builds
fi

if [ ! -d ${BUILDS} ]; then
	mkdir ${BUILDS}
fi

cd ${BUILDS}

cower -d emacspeak

if [ ! -d emacspeak ]; then
	echo "Failed to cower -d emacspeak"
	exit 1
fi

cd emacspeak

if [ ${ARCH} ]; then
	do_pkgbuild_edit || exit 1
fi

makepkg -s -i --noconfirm --noprogressbar

# check ~/.bashrc for 'export DTK_PROGRAM=espeak'
egrep "export\s+DTK_PROGRAM=espeak" ~/.bashrc
if [ $? -ne 0 ]; then
	echo "\nexport DTK_PROGRAM=espeak\n" >> ~/.bashrc
fi

echo "Finished running arch-install-emacspeak"

exit 0
