#!/bin/bash
#
# Gets, builds and installs cower
#

# Don't use relative path here so we can call this script from another
BUILD_PATH=~/.builds
ARCH="'armv6h'"

function do_pkgbuild_edit {
	( mv PKGBUILD PKGBUILD.old && cat PKGBUILD.old | perl -e "while(<>) {s/^arch=\('i686'\s+'x86_64'\)$/arch=\('i686' 'x86_64' ${ARCH}\)/;print;}" > PKGBUILD ) || return 1
	return 0
}


## main code


if [ ! -d ${BUILD_PATH} ]; then
	mkdir ${BUILD_PATH}
fi

cd ${BUILD_PATH}

( wget https://aur.archlinux.org/packages/co/cower-git/cower-git.tar.gz && tar -zxf cower-git.tar.gz ) || exit 1

cd cower-git

if [ ${ARCH} ]; then
	do_pkgbuild_edit || exit 1
fi


makepkg -s -i --noconfirm --noprogressbar || exit 1

echo "Finished running arch-install-cower"

exit 0




