#!/bin/bash
#
# This script will correctly install tclx from the AUR.
# I wrote this because the AUR Emacspeak package fails to find the tclx dependancy in
# the main repo, and because the AUR tclx package doesn't correctly install the tclx libraries
# that emacspeak needs to run.
#

# Don't use relative path here so that we can call this script from another
BUILD_PATH=~/.builds
ARCH="'armv6h'"

## functions

function do_pkgbuild_edit {
	( mv PKGBUILD PKGBUILD.old && cat PKGBUILD.old | perl -e "while(<>) {s/^arch=\('i686'\s+'x86_64'\)$/arch=\('i686' 'x86_64' ${ARCH}\)/;print;}" > PKGBUILD ) || return 1
	return 0
}

## main code


# set BUILD_PATH to a default value if it's not set in the script
if [ ! ${BUILD_PATH} ]; then
	${BUILD_PATH}=~/.builds
fi

if [ ! -d ${BUILD_PATH} ]; then
	mkdir ${BUILD_PATH}
fi

cd ${BUILD_PATH}

cower -d tclx
if [ ! $? ]; then
	echo "Failed to cower -d tclx"
	exit 1
fi

# change dir to the downloaded path
cd tclx


if [ ${ARCH} ]; then
	do_pkgbuild_edit || exit 1
fi

# make and install the package
makepkg -s -i --noconfirm --noprogressbar

# Need to copy a directory to where it should be
# See comments at top of this script
sudo cp -r pkg/usr/lib/tclx8.4/ /usr/lib

echo "Finished arch-install-tclx-properly"



