#!/bin/bash

export TEXTDOMAIN=rpi-image-tool
#export TEXTDOMAINDIR=$PWD/locale
export TEXTDOMAINDIR=/usr/local/share/locale

. gettext.sh

. rpi-image-tool.lib


usage() {
	USAGE=$(gettext "tool_usage")
	echo -e "${USAGE}"
}


#-- Main code

check_root RESULT

if [ ${RESULT} != 1 ]; then
	PROGNAME=$0
	echo $(eval_gettext "Script must be run as root, try: sudo \$PROGNAME") ; echo
	exit 1
fi


WORKDIR=
IMAGEFILE=
FUNCTION=
SPLIT=64
BLOCKSIZE=1M
BLOCKCOUNT=

BOOTMOUNTPOINT=boot
ROOTMOUNTPOINT=root


while getopts ':C:D:M:N:c:hs:w:z:' flag ; do
	case $flag in
	h)
		usage
		exit 0
	;;
C)
		FUNCTION=cleanup
		WORKDIR=${OPTARG}
		break 2
	;;
	D)
		FUNCTION=mountdevice
		DEVICE=${OPTARG}
	;;
	M)
		FUNCTION=mountimage
		IMAGEFILE=${OPTARG}
	;;
	N)
		FUNCTION=new
		IMAGEFILE=${OPTARG}
	;;
	c)
		BLOCKCOUNT=${OPTARG}
		validate_blockcount ${BLOCKCOUNT}
	;;
	s)
		SPLIT=${OPTARG}
		validate_split ${SPLIT}
	;;
	w)
		WORKDIR=${OPTARG}
	;;
	z)
		BLOCKSIZE=${OPTARG}
		validate_blocksize ${BLOCKSIZE}
	;;
	(?)
		echo $(gettext "Invalid option") >&2
		echo >&2
		usage
		exit 1
	;;
	:)
		echo $(eval_gettext "Option - \$OPTARG requires an argument.") >&2
		echo >&2
		usage
		exit 1
	;;
	esac
done

[ -z ${WORKDIR} ] && { echo $(gettext "Work directory not set") ; echo ; usage; exit 1 ; }

if [ ${FUNCTION} = 'mountimage' ] || [ $FUNCTION = 'new' ]; then
	[ -z "${IMAGEFILE}" ] && { echo $(gettext "Image file name not set") ; echo ; usage; exit 1 ; }
fi

if [ ${FUNCTION} = 'mountdevice' ]; then
	[ -z "${DEVICE}" ] && { echo $(gettext "Device name not set") ; echo ; usage ; exit 1 ; }
fi

if [ ${FUNCTION} = 'new' ]; then
	[ -z ${BLOCKCOUNT} ] && { echo $(gettext "Block count not set") ; echo ; usage ; exit 1 ; }
	[ -z ${BLOCKSIZE} ] && { echo $(gettext "Block size not set") ; echo ; usage ; exit 1 ; }
	[ -z ${SPLIT} ] && { echo $(gettext "Split size not set") ; echo ; usage ; exit 1 ; }
fi

case ${FUNCTION} in
	cleanup)
		clean_up ${WORKDIR}
# ${BOOTMP} ${ROOTMP}
	;;
	mountimage)
		mount_image ${WORKDIR} ${IMAGEFILE} ${BOOTMOUNTPOINT} ${ROOTMOUNTPOINT}
	;;
	mountdevice)
		mount_device ${WORKDIR} ${DEVICE} ${BOOTMOUNTPOINT} ${ROOTMOUNTPOINT}
	;;
	new)
		new_image ${WORKDIR} ${IMAGEFILE} ${BOOTMOUNTPOINT} ${ROOTMOUNTPOINT} ${BLOCKCOUNT} ${BLOCKSIZE} ${SPLIT}
	;;
esac

exit 0


